# docker-compose.yml for testing the auth service with PostgreSQL before deploying.
version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: miniblog_user
      POSTGRES_PASSWORD: miniblog_pass
      POSTGRES_DB: miniblog_auth
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
